import type { Metadata } from "next";
import Navbar from "../../components/Navbar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="font-work-sans">
        <Navbar/>
        {children}
    </main>
  );
}
